[package]
name = "day-3-mull-it-over"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
toolkit = { path = "../toolkit/" }
