[package]
name = "day-2-red-nosed-reports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component = "0.1.1"
itertools = "0.13.0"
rust-analyzer = "0.0.1"
toolkit = { path = "../toolkit/" }
